/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    id("java-library")
    id("maven-publish")   
    id("org.springframework.boot") version "2.7.18"
    id("io.spring.dependency-management") version "1.1.7" 
}
group = project.findProperty("buildGroup") as String 
version = project.findProperty("buildVersion") as String 
java { 
    toolchain {
        languageVersion.set(JavaLanguageVersion.of((findProperty("javaVersion") as String).toInt()))
    } 
    withSourcesJar()
    withJavadocJar()
}
tasks.named<org.springframework.boot.gradle.tasks.bundling.BootJar>("bootJar") {
    enabled = false
}
tasks.named<Jar>("jar") {
    enabled = true
}
dependencies {   
    // studio one
    compileOnly("studio.one.starter:studio-platform-starter:${property("studioOneVersion")}") 
    compileOnly("studio.one.starter:studio-platform-starter-user:${property("studioOneVersion")}")
    // spring boot
    compileOnly("org.springframework.boot:spring-boot-starter-validation") 
    compileOnly("org.springframework.boot:spring-boot-starter-aop") 
    compileOnly("org.springframework.boot:spring-boot-starter-web")
    compileOnly("org.springframework.boot:spring-boot-starter-data-jpa")
    compileOnly("org.springframework.boot:spring-boot-starter-security") 
    compileOnly("org.springframework.boot:spring-boot-starter-cache")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    // lombok
    val lombokVersion: String = project.findProperty("lombokVersion") as String? ?: "1.18.30"
    compileOnly("org.projectlombok:lombok:$lombokVersion")
    annotationProcessor("org.projectlombok:lombok:$lombokVersion")
	testCompileOnly("org.projectlombok:lombok:$lombokVersion")
    testAnnotationProcessor("org.projectlombok:lombok:$lombokVersion")
}
publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
            artifactId = "studio-one-pages" 
        }
    }
    repositories {
        maven {
            val allowInsecure = (findProperty("nexus.allowInsecure") as String).toBoolean()
            isAllowInsecureProtocol = allowInsecure 
            val isSnapshot = version.toString().endsWith("SNAPSHOT")
            url = uri(
                if (isSnapshot) (findProperty("nexus.snapshotsUrl") as String)
                else (findProperty("nexus.releasesUrl") as String)
            ) 
            credentials {
                username = (findProperty("nexus.username") as String?) ?: System.getenv("NEXUS_USERNAME")
                password = (findProperty("nexus.password") as String?) ?: System.getenv("NEXUS_PASSWORD")
            }
        }
    }
}